from modules.technology import Technology

# Electronic Techs that affect combat stats
class Radios(Technology):
    def __init__(self):
        Technology.__init__(self, name="Radios", efficiency=.03)

class InfRadCom:
    def __init__(self, level):
        def InfRadComTech(defensiveness, toughness):
            return Technology(name="Infantry Radio Communications", defensiveness = defensiveness, toughness = toughness)
        self.units = {}
        self.level = level
        self.units["infantry_brigade"] = InfRadComTech(.8, .5)
        self.units["colonial_infantry_brigade"] = InfRadComTech(.8, .5)
        self.units["infantry_bat"] = InfRadComTech(.8, .5)
        self.units["ss_infantry_bat"] = InfRadComTech(.8, .5)
        self.units["anzac_brigade"] = InfRadComTech(.8, .5)
        self.units["marine_brigade"] = InfRadComTech(.8, .5)
        self.units["naval_infantry_brigade"] = InfRadComTech(.8, .5)
        self.units["air_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["paratrooper_brigade"] = InfRadComTech(.8, .5)
        self.units["airborne_combined_arms_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_paratrooper_brigade"] = InfRadComTech(.8, .5)
        self.units["guard_paratrooper_brigade"] = InfRadComTech(.8, .5)
        self.units["garrison_brigade"] = InfRadComTech(.8, .5)
        self.units["tropical_island_garrison_brigade"] = InfRadComTech(.8, .5)
        self.units["garrison_detachment"] = InfRadComTech(.8, .5)
        self.units["colonial_garrison_brigade"] = InfRadComTech(.8, .5)
        self.units["luftwaffe_brigade"] = InfRadComTech(.8, .5)
        self.units["HQDEF_brigade"] = InfRadComTech(.8, .5)
        self.units["bergsjaeger_brigade"] = InfRadComTech(.8, .5)
        self.units["colonial_bergsjaeger_brigade"] = InfRadComTech(.8, .5)
        self.units["motorized_brigade"] = InfRadComTech(.8, .5)
        self.units["motorized_infantry_bat"] = InfRadComTech(.4, .15)
        self.units["semi_motorized_brigade"] = InfRadComTech(.8, .5)
        self.units["mechanized_brigade"] = InfRadComTech(.8, .5)
        self.units["mechanized_infantry_bat"] = InfRadComTech(.5, .15)
        self.units["combined_arms_brigade"] = InfRadComTech(.8, .5)
        self.units["light_infantry_brigade"] = InfRadComTech(.7, .5)
        self.units["colonial_light_infantry_brigade"] = InfRadComTech(.7, .5)
        self.units["airlanding_infantry_brigade"] = InfRadComTech(.7, .5)
        self.units["elite_light_infantry_brigade"] = InfRadComTech(.7, .5)
        self.units["elite_light_infantry_battalion"] = InfRadComTech(.7, .5)
        self.units["NKVD_brigade"] = InfRadComTech(.8, .5)
        self.units["police_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_police_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_motorized_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_totenkopf"] = InfRadComTech(.8, .5)
        self.units["ss_lssah"] = InfRadComTech(.8, .5)
        self.units["ss_wiking"] = InfRadComTech(.8, .5)
        self.units["grossdeutschland_brigade"] = InfRadComTech(.8, .5)
        self.units["lehr_brigade"] = InfRadComTech(.8, .5)
        self.units["afrika_brigade"] = InfRadComTech(.8, .5)
        self.units["goering_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_dasreich"] = InfRadComTech(.8, .5)
        self.units["ss_frundsberg"] = InfRadComTech(.8, .5)
        self.units["ss_hohenstaufen"] = InfRadComTech(.8, .5)
        self.units["ss_hitlerjugend"] = InfRadComTech(.8, .5)
        self.units["ss_polizei"] = InfRadComTech(.8, .5)
        self.units["ss_mechanized_brigade"] = InfRadComTech(.8, .5)
        self.units["guard_mechanized_brigade"] = InfRadComTech(.8, .5)
        self.units["guard_infantry_brigade"] = InfRadComTech(.8, .5)
        self.units["guard_motorized_brigade"] = InfRadComTech(.8, .5)
        self.units["commando_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_commando_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_infantry_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_bergsjaeger_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_prinz_eugen"] = InfRadComTech(.8, .5)
        self.units["Gurkha_brigade"] = InfRadComTech(.8, .5)
        self.units["ski_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_ski_brigade"] = InfRadComTech(.8, .5)
        self.units["cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["colonial_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["Recon_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_Recon_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["ger_sa_cavalry_detachment"] = InfRadComTech(.8, .5)
        self.units["motorcycle_recon_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_motorcycle_recon_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["ger_sa_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_florian_geyer"] = InfRadComTech(.8, .5)
        self.units["guard_cavalry_brigade"] = InfRadComTech(.8, .5)
        self.units["engineer_brigade"] = InfRadComTech(.8, .5)
        self.units["airborne_engineer_bat"] = InfRadComTech(.8, .5)
        self.units["motorized_engineer_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_motorized_engineer_brigade"] = InfRadComTech(.8, .5)
        self.units["ss_engineer_brigade"] = InfRadComTech(.8, .5)
        self.units["militia_brigade"] = InfRadComTech(.8, .5)
        self.units["colonial_militia_brigade"] = InfRadComTech(.8, .5)
        self.units["partisan_brigade"] = InfRadComTech(.8, .5)
        self.units["fascist_militia_brigade"] = InfRadComTech(.8, .5)
        self.units["ger_sa_militia_brigade"] = InfRadComTech(.8, .5)
        self.units["ger_sa_militia_detachment"] = InfRadComTech(.8, .5)
        self.units["Communist_militia_brigade"] = InfRadComTech(.8, .5)

class TankRadCom:
    def __init__(self, level):
        def TankRadComTech(defensiveness, toughness, organization):
            return Technology(name = "Tank Radio Communications", defensiveness = defensiveness, toughness = toughness, organization = organization)

        self.units = {}
        self.level = level
        self.units["armored_car_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_armored_car_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["captured_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["light_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["light_armor_bat"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_light_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_light_armor_bat"] = TankRadComTech(2, 1.5, 2)
        self.units["armored_engineers_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_armored_engineers_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["amph_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["combined_arms_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["desertrats_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["armored_support_brigade"] = TankRadComTech(0.2, 0.5, 2)
        self.units["ss_armored_support_brigade"] = TankRadComTech(0.2, 0.5, 2)
        self.units["armor_bat"] = TankRadComTech(2, 1.5, 2)
        self.units["heavy_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_heavy_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["guard_heavy_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["super_heavy_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["infantry_tank_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["guard_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_armor_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["assault_gun_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["heavy_assault_gun_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["tank_destroyer_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["medium_tank_destroyer_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["heavy_tank_destroyer_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_light_tank_destroyer_brigade"] = TankRadComTech(2, 1.5, 2)
        self.units["ss_tank_destroyer_brigade"] = TankRadComTech(2, 1.5, 2)

# Infantry Techs that affect combat stats
class SmallArms:
    def __init__(self, level):
        def SmallArmsTech(organization=0, softAttack=0, toughness=0, defensiveness=0):
            return Technology(name = "Small Arms", organization=organization, softAttack=softAttack, toughness=toughness, defensiveness=defensiveness)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = SmallArmsTech(.1)
        self.units["GER_hftrack_transport"] = SmallArmsTech(.1)
        self.units["FRA_hftrack_transport"] = SmallArmsTech(.1)
        self.units["truck_transport"] = SmallArmsTech(.1)
        self.units["civilian_truck_transport"] = SmallArmsTech(.1)
        self.units["ENG_truck_transport"] = SmallArmsTech(.1)
        self.units["GER_truck_transport"] = SmallArmsTech(.1)
        self.units["USA_truck_transport"] = SmallArmsTech(.1)
        self.units["FRA_truck_transport"] = SmallArmsTech(.1)
        self.units["light_transport"] = SmallArmsTech(.1)
        self.units["USA_light_transport"] = SmallArmsTech(.1)
        self.units["ITA_light_transport"] = SmallArmsTech(.1)
        self.units["horse_transport"] = SmallArmsTech(.2)
        self.units["camel_transport"] = SmallArmsTech(.2)
        self.units["SOV_horse_transport"] = SmallArmsTech(.2)
        self.units["air_cavalry_brigade"] = SmallArmsTech(softAttack=3, toughness=1.3, defensiveness=2.3)
        self.units["Gurkha_brigade"] = SmallArmsTech(softAttack=0.7, toughness=1.3, defensiveness=2.3)
        self.units["commando_brigade"] = SmallArmsTech(softAttack=1.1, toughness=1.5, defensiveness=2.5)
        self.units["ss_commando_brigade"] = SmallArmsTech(softAttack=1.3, toughness=1.5, defensiveness=2.5)
        self.units["engineer_brigade"] = SmallArmsTech(softAttack=0.5, toughness=1.3, defensiveness=2)
        self.units["airborne_engineer_bat"] = SmallArmsTech(softAttack=0.5, toughness=1.5, defensiveness=2.3)
        self.units["motorized_engineer_brigade"] = SmallArmsTech(softAttack=0.5, toughness=1.3, defensiveness=2)
        self.units["ss_motorized_engineer_brigade"] = SmallArmsTech(softAttack=0.5, toughness=1.5, defensiveness=2.3)
        self.units["ss_engineer_brigade"] = SmallArmsTech(softAttack=0.5, toughness=1.5, defensiveness=2.3)
        self.units["motorcycle_recon_brigade"] = SmallArmsTech(softAttack=1.3)
        self.units["ss_motorcycle_recon_brigade"] = SmallArmsTech(softAttack=1.3)
        self.units["Recon_cavalry_brigade"] = SmallArmsTech(softAttack=1.2)
        self.units["ss_Recon_cavalry_brigade"] = SmallArmsTech(softAttack=1.2)
        self.units["ger_sa_cavalry_detachment"] = SmallArmsTech(softAttack=1.2)
        self.units["combined_arms_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["police_brigade"] = SmallArmsTech(softAttack=1.1)
        self.units["ss_police_brigade"] = SmallArmsTech(softAttack=1.1)
        self.units["NKVD_brigade"] = SmallArmsTech(softAttack=1.5)
        self.units["partisan_brigade"] = SmallArmsTech(softAttack=1)
        self.units["hq_brigade"] = SmallArmsTech(softAttack=.75)
        self.units["mot_hq_brigade"] = SmallArmsTech(softAttack=1.3)
        self.units["mech_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["armor_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["mountain_infantry_hq_brigade"] = SmallArmsTech(softAttack=1.3)
        self.units["marine_hq_brigade"] = SmallArmsTech(softAttack=1.5)
        self.units["para_hq_brigade"] = SmallArmsTech(softAttack=1.5)
        self.units["ss_hq_brigade"] = SmallArmsTech(softAttack=1.5)
        self.units["ger_sa_hq_brigade"] = SmallArmsTech(softAttack=1)
        self.units["ss_mot_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["ss_mech_hq_brigade"] = SmallArmsTech(softAttack=1.8)
        self.units["ss_pz_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["guard_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["guard_mot_hq_brigade"] = SmallArmsTech(softAttack=1.7)
        self.units["guard_mech_hq_brigade"] = SmallArmsTech(softAttack=1.8)
        self.units["guard_armor_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["guard_para_hq_brigade"] = SmallArmsTech(softAttack=1.6)
        self.units["shock_hq_brigade"] = SmallArmsTech(softAttack=1.6)

class InfantrySupportWep:
    def __init__(self, level):
        def InfSupWepTech(defensiveness):
            return Technology("Infantry Support Weapons", defensiveness = defensiveness)

        self.units = {}
        self.level = level
        self.units["air_cavalry_brigade"] = InfSupWepTech(5)
        self.units["Gurkha_brigade"] = InfSupWepTech(4)
        self.units["commando_brigade"] = InfSupWepTech(2.5)
        self.units["ss_commando_brigade"] = InfSupWepTech(2.5)
        self.units["motorcycle_recon_brigade"] = InfSupWepTech(.2)
        self.units["ss_motorcycle_recon_brigade"] = InfSupWepTech(.2)
        self.units["Recon_cavalry_brigade"] = InfSupWepTech(.15)
        self.units["ss_Recon_cavalry_brigade"] = InfSupWepTech(.15)
        self.units["ger_sa_cavalry_brigade"] = InfSupWepTech(.15)
        self.units["combined_arms_brigade"] = InfSupWepTech(4)
        self.units["partisan_brigade"] = InfSupWepTech(3.3)
        self.units["mixed_support_brigade"] = InfSupWepTech(3.5)
        self.units["airborne_artillery_brigade"] = InfSupWepTech(3)
        self.units["ss_mixed_support_brigade"] = InfSupWepTech(3.5)

class InfantryGuns:
    def __init__(self, level):
        def InfGunsTech(toughness=0, softAttack=0):
            return Technology("Infantry Guns", toughness = toughness, softAttack = softAttack)

        self.units = {}
        self.level = level
        self.units["air_cavalry_brigade"] = InfGunsTech(1.3, 1.8)
        self.units["Gurkha_brigade"] = InfGunsTech(1.3, 1.5)
        self.units["combined_arms_brigade"] = InfGunsTech(1.3, 1)
        self.units["artillery_brigade"] = InfGunsTech(0.1)
        self.units["ss_artillery_brigade"] = InfGunsTech(0.1)
        self.units["medium_artillery_brigade"] = InfGunsTech(0.1)
        self.units["ss_medium_artillery_brigade"] = InfGunsTech(0.1)
        self.units["pack_artillery_brigade"] = InfGunsTech(0.1)
        self.units["ss_pack_artillery_brigade"] = InfGunsTech(0.1)
        self.units["mixed_support_brigade"] = InfGunsTech(0.04)
        self.units["airborne_artillery_brigade"] = InfGunsTech(0.08)
        self.units["ss_mixed_support_brigade"] = InfGunsTech(0.07)
        self.units["motorized_support_brigade"] = InfGunsTech(0.04)
        self.units["ss_motorized_support_brigade"] = InfGunsTech(0.07)
        self.units["partisan_brigade"] = InfGunsTech(0.12, 0.3)

class InfantryATWep:
    def __init__(self, level):
        def InfATWepTech(hardAttack=0, piercing=0):
            return Technology("Infantry Anti-Tank Weapons", hardAttack = hardAttack, piercing = piercing)

        self.units = {}
        self.level = level
        self.units["air_cavalry_brigade"] = InfATWepTech(0.9, 2.2)
        self.units["Gurkha_brigade"] = InfATWepTech(0.45, 2)
        self.units["commando_brigade"] = InfATWepTech(0.45, 1)
        self.units["ss_commando_brigade"] = InfATWepTech(0.45, 1)
        self.units["combined_arms_brigade"] = InfATWepTech(0.45, 2)
        self.units["partisan_brigade"] = InfATWepTech(0.4, 1)
        self.units["mixed_support_brigade"] = InfATWepTech(0.4)
        self.units["airborne_artillary_brigade"] = InfATWepTech(0.4)
        self.units["ss_mixed_support_brigade"] = InfATWepTech(0.4)

class AssaultRifles:
    def __init__(self, level):
        def AssaultRiflesTech(softAttack, defensiveness):
            return Technology("Assault Rifles", softAttack = softAttack, defensiveness = defensiveness)

        self.units = {}
        self.level = level
        self.units["garrison_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["tropical_island_garrison_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["garrison_detachment"] = AssaultRiflesTech(4.5, 4.5)
        self.units["colonial_garrison_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["luftwaffe_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["ss_garrison_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["militia_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["colonial_militia_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["fascist_militia_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ger_sa_militia_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ger_sa_militia_detachment"] = AssaultRiflesTech(2.4, 2.4)
        self.units["Communist_militia_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["infantry_brigade"] = AssaultRiflesTech(5.2, 5.2)
        self.units["colonial_infantry_brigade"] = AssaultRiflesTech(5.2, 5.2)
        self.units["infantry_bat"] = AssaultRiflesTech(2.6, 5.2)
        self.units["ss_infantry_bat"] = AssaultRiflesTech(2.6, 5.2)
        self.units["anzac_brigade"] = AssaultRiflesTech(5.2, 5.2)
        self.units["light_infantry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["colonial_light_infantry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["elite_light_infantry_battalion"] = AssaultRiflesTech(5, 5)
        self.units["elite_light_infantry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["ss_infantry_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["guard_infantry_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["airlanding_infantry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["air_cavalry_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["ski_brigade"] = AssaultRiflesTech(5.3, 5.3)
        self.units["ss_ski_brigade"] = AssaultRiflesTech(5.3, 5.3)
        self.units["Gurkha_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["naval_infantry_brigade"] = AssaultRiflesTech(5.2, 5.2)
        self.units["marine_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["paratrooper_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["airborne_combined_arms_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["ss_paratrooper_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["guard_paratrooper_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["commando_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["ss_commando_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["engineer_brigade"] = AssaultRiflesTech(4.4, 4.4)
        self.units["airborne_engineer_brigade"] = AssaultRiflesTech(4.4, 4.4)
        self.units["motorized_engineer_brigade"] = AssaultRiflesTech(4.4, 4.4)
        self.units["ss_motorized_engineer_brigade"] = AssaultRiflesTech(4.4, 4.4)
        self.units["ss_engineer_brigade"] = AssaultRiflesTech(4.4, 4.4)
        self.units["cavalry_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["colonial_cavalry_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ss_cavalry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["ger_sa_cavalry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["guard_cavalry_brigade"] = AssaultRiflesTech(5, 5)
        self.units["motorcycle_recon_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ss_motorcycle_recon_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["semi_motorized_brigade"] = AssaultRiflesTech(5, 5)
        self.units["motorized_brigade"] = AssaultRiflesTech(5.4, 5.4)
        self.units["ss_motorized_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["guard_motorized_brigade"] = AssaultRiflesTech(5.5, 5.5)
        self.units["mechanized_brigade"] = AssaultRiflesTech(5.6, 5.6)
        self.units["ss_mechanized_brigade"] = AssaultRiflesTech(5.7, 5.7)
        self.units["guard_mechanized_brigade"] = AssaultRiflesTech(5.7, 5.7)
        self.units["Recon_cavalry_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ss_Recon_cavalry_brigade"] = AssaultRiflesTech(4.8, 4.8)
        self.units["ger_sa_cavalry_detachment"] = AssaultRiflesTech(2.4, 2.4)
        self.units["combined_arms_brigade"] = AssaultRiflesTech(5.6, 5.6)
        self.units["motorized_infantry_bat"] = AssaultRiflesTech(3.4, 3.4)
        self.units["ss_motorized_infantry_bat"] = AssaultRiflesTech(3.4, 3.4)
        self.units["mechanized_infantry_bat"] = AssaultRiflesTech(3.6, 3.6)
        self.units["ss_mechanized_infantry_bat"] = AssaultRiflesTech(3.6, 3.6)
        self.units["police_brigade"] = AssaultRiflesTech(4.1, 4.1)
        self.units["ss_polizei"] = AssaultRiflesTech(5, 5)
        self.units["ss_police_brigade"] = AssaultRiflesTech(4.1, 4.1)
        self.units["NKVD_brigade"] = AssaultRiflesTech(4.5, 4.5)
        self.units["partisan_brigade"] = AssaultRiflesTech(4, 4)
        self.units["ss_prinz_eugen"] = AssaultRiflesTech(5.5, 5.5)
        self.units["ss_totenkopf"] = AssaultRiflesTech(5.8, 5.8)
        self.units["ss_lssah"] = AssaultRiflesTech(5.8, 5.8)
        self.units["ss_wiking"] = AssaultRiflesTech(5.7, 5.7)
        self.units["ss_dasreich"] = AssaultRiflesTech(5.8, 5.8)
        self.units["ss_frundsberg"] = AssaultRiflesTech(5.5, 5.5)
        self.units["ss_hohenstaufen"] = AssaultRiflesTech(5.5, 5.5)
        self.units["ss_hitlerjugend"] = AssaultRiflesTech(5.7, 5.7)
        self.units["grossdeutschland_brigade"] = AssaultRiflesTech(5.8, 5.8)
        self.units["lehr_brigade"] = AssaultRiflesTech(5.8, 5.8)
        self.units["afrika_brigade"] = AssaultRiflesTech(5.8, 5.8)
        self.units["ss_florian_geyer"] = AssaultRiflesTech(5.4, 5.4)
        self.units["goering_brigade"] = AssaultRiflesTech(5.8, 5.8)
        self.units["HQDEF_brigade"] = AssaultRiflesTech(4.5, 4.5)

class RocketAT:
    def __init__(self, level):
        def RocketATTech(hardAttack, piercing):
            return Technology("Rocket Propelled Anti Tank Weapons", hardAttack = hardAttack, piercing = piercing)

        self.units = {}
        self.level = level
        self.units["infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["anzac_brigade"] = RocketATTech(1.5, 2.5)
        self.units["colonial_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["infantry_bat"] = RocketATTech(0.8, 2.5)
        self.units["ss_infantry_bat"] = RocketATTech(0.8, 2.5)
        self.units["luftwaffe_brigade"] = RocketATTech(1.5, 2.5)
        self.units["marine_brigade"] = RocketATTech(1.5, 2.5)
        self.units["paratrooper_brigade"] = RocketATTech(1.5, 2.5)
        self.units["airborne_combined_arms_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_paratrooper_brigade"] = RocketATTech(1.5, 2.5)
        self.units["garrison_brigade"] = RocketATTech(1.5, 2.5)
        self.units["tropical_island_garrison_brigade"] = RocketATTech(1.5, 2.5)
        self.units["garrison_detachment"] = RocketATTech(1.5, 2.5)
        self.units["colonial_garrison_brigade"] = RocketATTech(1.5, 2.5)
        self.units["bergsjaeger_brigade"] = RocketATTech(1.5, 2.5)
        self.units["colonial_bergsjaeger_brigade"] = RocketATTech(1.5, 2.5)
        self.units["motorized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["motorized_infantry_bat"] = RocketATTech(1.5, 2.5)
        self.units["ss_mechanized_infantry_bat"] = RocketATTech(1.5, 2.5)
        self.units["ss_motorized_infantry_bat"] = RocketATTech(1.5, 2.5)
        self.units["mechanized_infantry_bat"] = RocketATTech(1.5, 2.5)
        self.units["semi_motorized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["mechanized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["combined_arms_brigade"] = RocketATTech(1.5, 2.5)
        self.units["light_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["colonial_light_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["airlanding_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["elite_light_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["elite_light_infantry_battalion"] = RocketATTech(1.5, 2.5)
        self.units["NKVD_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_motorized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_totenkopf"] = RocketATTech(1.5, 2.5)
        self.units["ss_lssah"] = RocketATTech(1.5, 2.5)
        self.units["ss_wiking"] = RocketATTech(1.5, 2.5)
        self.units["ss_dasreich"] = RocketATTech(1.5, 2.5)
        self.units["ss_frundsberg"] = RocketATTech(1.5, 2.5)
        self.units["ss_hohenstaufen"] = RocketATTech(1.5, 2.5)
        self.units["ss_hitlerjugend"] = RocketATTech(1.5, 2.5)
        self.units["ss_polizei"] = RocketATTech(1.5, 2.5)
        self.units["grossdeutschland_brigade"] = RocketATTech(1.5, 2.5)
        self.units["lehr_brigade"] = RocketATTech(1.5, 2.5)
        self.units["afrika_brigade"] = RocketATTech(1.5, 2.5)
        self.units["goering_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_mechanized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["guard_mechanized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["guard_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["guard_motorized_brigade"] = RocketATTech(1.5, 2.5)
        self.units["guard_paratrooper_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ski_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_ski_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_bergsjaeger_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_prinz_eugen"] = RocketATTech(1.5, 2.5)
        self.units["Gurkha_brigade"] = RocketATTech(1.5, 2.5)
        self.units["commando_brigade"] = RocketATTech(1.5, 2.5)
        self.units["ss_commando_brigade"] = RocketATTech(1.5, 2.5)
        self.units["naval_infantry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["air_cavalry_brigade"] = RocketATTech(1.5, 2.5)
        self.units["Communist_militia_brigade"] = RocketATTech(1, 2.5)
        self.units["militia_brigade"] = RocketATTech(1, 2.5)
        self.units["colonial_militia_brigade"] = RocketATTech(1, 2.5)
        self.units["fascist_militia_brigade"] = RocketATTech(1, 2.5)
        self.units["ger_sa_militia_brigade"] = RocketATTech(1, 2.5)
        self.units["ger_sa_militia_detachment"] = RocketATTech(1, 2.5)
        self.units["cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["colonial_cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["ss_cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["ger_sa_cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["ss_florian_geyer"] = RocketATTech(1, 2.5)
        self.units["Recon_cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["motorcycle_recon_brigade"] = RocketATTech(1, 2.5)
        self.units["engineer_brigade"] = RocketATTech(1, 2.5)
        self.units["airborne_engineer_bat"] = RocketATTech(1, 2.5)
        self.units["motorized_engineer_brigade"] = RocketATTech(1, 2.5)
        self.units["ss_motorized_engineer_brigade"] = RocketATTech(1, 2.5)
        self.units["ss_Recon_cavalry_brigade"] = RocketATTech(1, 2.5)
        self.units["ger_sa_cavalry_detachment"] = RocketATTech(1, 2.5)
        self.units["ss_motorcycle_recon_brigade"] = RocketATTech(1, 2.5)
        self.units["ss_engineer_brigade"] = RocketATTech(1, 2.5)

class StdInfBrUpg:
    def __init__(self, level):
        def StdInfBrUpgTech(toughness=0, defensiveness=0, softAttack=0, hardAttack=0, piercing=0, armor=0):
            return Technology("Standard Infantry Branch Upgrade", toughness = toughness, 
                defensiveness = defensiveness, softAttack = softAttack, hardAttack = hardAttack, piercing = piercing, armor = armor)

        self.units = {}
        self.level = level
        self.units["infantry_brigade"] = StdInfBrUpgTech(1, 3, 2.3, 0.8, 1.5)
        self.units["colonial_infantry_brigade"] = StdInfBrUpgTech(1, 3, 2.3, 0.8, 1.5)
        self.units["infantry_bat"] = StdInfBrUpgTech(1, 3, 1.2, 0.4, 1.5)
        self.units["ss_infantry_bat"] = StdInfBrUpgTech(1, 3, 1.2, 0.4, 1.5)
        self.units["ss_infantry_brigade"] = StdInfBrUpgTech(1.2, 3.2, 2.4, 0.85, 1.5)
        self.units["guard_infantry_brigade"] = StdInfBrUpgTech(1.2, 3.2, 2.4, 0.85, 1.5)
        self.units["anzac_brigade"] = StdInfBrUpgTech(1.2, 3.2, 2.4, 0.85, 1.5)
        self.units["semi_motorized_brigade"] = StdInfBrUpgTech(1, 3, 2.3, 0.8, 1.5)
        self.units["motorized_brigade"] = StdInfBrUpgTech(1.2, 3.2, 2.6, 1.2, 2)
        self.units["motorized_infantry_bat"] = StdInfBrUpgTech(1.2, 3.2, 1.3, 0.6, 2)
        self.units["ss_motorized_brigade"] = StdInfBrUpgTech(1.4, 3.4, 2.7, 1.2, 2)
        self.units["ss_motorized_bat"] = StdInfBrUpgTech(1.4, 3.4, 1.4, 0.6, 2)
        self.units["ss_polizei"] = StdInfBrUpgTech(1.4, 3.5, 2.7, 1.2, 2)
        self.units["guard_motorized_brigade"] = StdInfBrUpgTech(1.4, 3.5, 2.7, 1.2, 2)
        self.units["mechanized_brigade"] = StdInfBrUpgTech(1.6, 3.8, 3, 2, 3, 1)
        self.units["ss_mechanized_brigade"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["mechanized_infantry_bat"] = StdInfBrUpgTech(1.6, 3.8, 1.5, 1, 3, 1)
        self.units["ss_mechanized_infantry_bat"] = StdInfBrUpgTech(1.8, 4, 1.5, 1, 3, 1)
        self.units["guard_mechanized_brigade"] = StdInfBrUpgTech(1.8, 3.8, 3, 2, 3, 1)
        self.units["afrika_brigade"] = StdInfBrUpgTech(1.8, 3.8, 3, 2, 3, 1)
        self.units["grossdeutschland_brigade"] = StdInfBrUpgTech(2, 4, 3.3, 2.3, 4, 1.5)
        self.units["lehr_brigade"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["goering_brigade"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["ss_totenkopf"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["ss_lssah"] = StdInfBrUpgTech(2, 4, 3.3, 2.3, 4, 1.5)
        self.units["ss_wiking"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["ss_dasreich"] = StdInfBrUpgTech(1.8, 4, 3, 2, 3, 1)
        self.units["ss_frundsberg"] = StdInfBrUpgTech(1.8, 3.8, 2.7, 1.2, 2)
        self.units["ss_hohenstaufen"] = StdInfBrUpgTech(1.8, 3.8, 2.7, 1.2, 2)
        self.units["ss_hitlerjugend"] = StdInfBrUpgTech(2, 4, 3, 2, 3, 1)
        self.units["garrison_brigade"] = StdInfBrUpgTech(0.8, 3.4, 1.8, 0.5, 1, 1)
        self.units["tropical_island_garrison_brigade"] = StdInfBrUpgTech(0.8, 3.4, 1.8, 0.5, 1, 1)
        self.units["garrison_detachment"] = StdInfBrUpgTech(0.8, 3.4, 1.8, 0.5, 1, 1)
        self.units["colonial_garrison_brigade"] = StdInfBrUpgTech(0.8, 3.4, 1.8, 0.5, 1, 1)
        self.units["ss_garrison_brigade"] = StdInfBrUpgTech(0.8, 3.4, 1.8, 0.5, 1, 1)

class LightInfBrUpg:
    def __init__(self, level):
        def LightInfBrUpgTech(toughness = 0, defensiveness = 0, softAttack = 0, hardAttack = 0, piercing = 0):
            return Technology("Light Infantry Branch Upgrade", toughness = toughness, defensiveness = defensiveness, 
                softAttack = softAttack, hardAttack = hardAttack, piercing = piercing)

        self.units = {}
        self.level = level
        self.units["bergsjaeger_brigade"] = LightInfBrUpgTech(1, 2.4, 1.5, 0.3, 0.5)
        self.units["colonial_bergsjaeger_brigade"] = LightInfBrUpgTech(1, 2.4, 1.5, 0.3, 0.5)
        self.units["ss_bergsjaeger_brigade"] = LightInfBrUpgTech(1, 2.4, 1.5, 0.3, 0.5)
        self.units["ss_prinz_eugen"] = LightInfBrUpgTech(1, 2.4, 1.5, 0.3, 0.5)
        self.units["airlanding_infantry_brigade"] = LightInfBrUpgTech(1, 2.4, 1.8, 0.5, 0.7)
        self.units["light_infantry_brigade"] = LightInfBrUpgTech(1.2, 2.3, 1.4, 0.3, 0.5)
        self.units["colonial_light_infantry_brigade"] = LightInfBrUpgTech(1.2, 2.3, 1.4, 0.3, 0.5)
        self.units["ski_brigade"] = LightInfBrUpgTech(1, 2.3, 1.4, 0.3, 0.5)
        self.units["ss_ski_brigade"] = LightInfBrUpgTech(1, 2.3, 1.4, 0.3, 0.5)
        self.units["naval_infantry_brigade"] = LightInfBrUpgTech(1.2, 2.3, 1.4, 0.3, 0.5)
        self.units["cavalry_brigade"] = LightInfBrUpgTech(1.2, 2.4, 1.2, 0.4, 0.5)
        self.units["colonial_cavalry_brigade"] = LightInfBrUpgTech(1.2, 2.4, 1.2, 0.4, 0.5)
        self.units["ss_cavalry_brigade"] = LightInfBrUpgTech(1.4, 2.6, 1.2, 0.4, 0.5)
        self.units["ger_sa_cavalry_brigade"] = LightInfBrUpgTech(1.2, 2.6, 1.2, 0.4, 0.5)
        self.units["ss_florian_geyer"] = LightInfBrUpgTech(1.4, 2.8, 1.2, 0.4, 0.5)
        self.units["guard_cavalry_brigade"] = LightInfBrUpgTech(1.6, 2.8, 1.2, 0.4, 0.5)
        self.units["militia_brigade"] = LightInfBrUpgTech(0.7, 1.9, 0.8, 0.5, 0.3)
        self.units["colonial_militia_brigade"] = LightInfBrUpgTech(0.7, 1.9, 0.8, 0.5, 0.3)
        self.units["fascist_militia_brigade"] = LightInfBrUpgTech(0.7, 1.9, 0.8, 0.5, 0.3)
        self.units["ger_sa_militia_brigade"] = LightInfBrUpgTech(0.7, 1.9, 0.8, 0.5, 0.3)
        self.units["ger_sa_militia_detachment"] = LightInfBrUpgTech(0.7, 1.9, 0.4, 0.25, 0.3)
        self.units["Communist_militia_brigade"] = LightInfBrUpgTech(0.7, 1.9, 0.8, 0.5, 0.3)
        self.units["HQDEF_brigade"] = LightInfBrUpgTech(1.2, 3.6, 1.8, 0.4, 0.5)
        self.units["luftwaffe_brigade"] = LightInfBrUpgTech(0.9, 2.2, 1.6, 0.4, 0.5)
        self.units["conscript_brigade"] = LightInfBrUpgTech(0.7, 4.4, 0.5, 0.5, 0.5)

class MotorizedInfantry:
    def __init__(self, level):
        def MotorizedInfTech(organization):
            return Technology("Motorization of Infantry", organization = organization)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = MotorizedInfTech(0.2)
        self.units["GER_hftrack_transport"] = MotorizedInfTech(0.2)
        self.units["FRA_hftrack_transport"] = MotorizedInfTech(0.2)
        self.units["truck_transport"] = MotorizedInfTech(0.2)
        self.units["civilian_truck_transport"] = MotorizedInfTech(0.2)
        self.units["ENG_truck_transport"] = MotorizedInfTech(0.2)
        self.units["GER_truck_transport"] = MotorizedInfTech(0.2)
        self.units["USA_truck_transport"] = MotorizedInfTech(0.2)
        self.units["FRA_truck_transport"] = MotorizedInfTech(0.2)
        self.units["light_transport"] = MotorizedInfTech(0.2)
        self.units["USA_light_transport"] = MotorizedInfTech(0.2)
        self.units["ITA_light_transport"] = MotorizedInfTech(0.2)

class MechanizedInfantry:
    def __init__(self, level):
        def MechanizedInfTech(organization=0, softness=0):
            return Technology("Mechanization of Infantry", organization = organization, softness=softness)

        self.units = {}
        self.level = level
        self.units["htrack_transport"] = MechanizedInfTech(0.3)
        self.units["GER_htrack_transport"] = MechanizedInfTech(0.3)
        self.units["FRA_htrack_transport"] = MechanizedInfTech(0.3)
        self.units["ss_totenkopf"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_lssah"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_wiking"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_dasreich"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_hitlerjugend"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_frundsberg"] = MechanizedInfTech(softness=-0.2)
        self.units["ss_hohenstaufen"] = MechanizedInfTech(softness=-0.2)
        self.units["grossdeutschland_brigade"] = MechanizedInfTech(softness=-0.2)
        self.units["lehr_brigade"] = MechanizedInfTech(softness=-0.2)
        self.units["afrika_brigade"] = MechanizedInfTech(softness=-0.2)
        self.units["goering_brigade"] = MechanizedInfTech(softness=-0.2)

class MotorizedCavalry:
    def __init__(self, level):
        def MotorizedCavalryTech(organization = 0, toughness = 0, softness = 0):
            return Technology("Motorization of Cavalry", organization = organization, toughness = toughness, softness = softness)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = MotorizedCavalryTech(.1)
        self.units["GER_hftrack_transport"] = MotorizedCavalryTech(.1)
        self.units["FRA_hftrack_transport"] = MotorizedCavalryTech(.1)
        self.units["truck_transport"] = MotorizedCavalryTech(.1)
        self.units["civilian_truck_transport"] = MotorizedCavalryTech(.1)
        self.units["ENG_truck_transport"] = MotorizedCavalryTech(.1)
        self.units["GER_truck_transport"] = MotorizedCavalryTech(.1)
        self.units["USA_truck_transport"] = MotorizedCavalryTech(.1)
        self.units["FRA_truck_transport"] = MotorizedCavalryTech(.1)
        self.units["light_transport"] = MotorizedCavalryTech(.1)
        self.units["USA_light_transport"] = MotorizedCavalryTech(.1)
        self.units["ITA_light_transport"] = MotorizedCavalryTech(.1)
        self.units["cavalry_brigade"] = MotorizedCavalryTech(toughness = 0.5, softness = -0.1)
        self.units["colonial_cavalry_brigade"] = MotorizedCavalryTech(toughness = 0.5, softness = -0.1)
        self.units["guard_cavalry_brigade"] = MotorizedCavalryTech(toughness = 0.7, softness = -0.1)
        self.units["ss_cavalry_brigade"] = MotorizedCavalryTech(toughness = 0.6, softness = -0.1)
        self.units["gar_sa_cavalry_brigade"] = MotorizedCavalryTech(toughness = 0.6, softness = -0.1)
        self.units["ss_florian_geyer"] = MotorizedCavalryTech(toughness = 0.6, softness = -0.1)

class BridgingEquipment:
    def __init__(self, level):
        def BridgingEquipmentTech(organization = 0, riverAttack = 0):
            return Technology("Bridging Equipment", organization = organization, riverAttack = riverAttack)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = BridgingEquipmentTech(-0.1)
        self.units["GER_hftrack_transport"] = BridgingEquipmentTech(-0.1)
        self.units["FRA_hftrack_transport"] = BridgingEquipmentTech(-0.1)
        self.units["truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["civilian_truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["ENG_truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["GER_truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["USA_truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["FRA_truck_transport"] = BridgingEquipmentTech(-0.1)
        self.units["light_transport"] = BridgingEquipmentTech(-0.1)
        self.units["USA_light_transport"] = BridgingEquipmentTech(-0.1)
        self.units["ITA_light_transport"] = BridgingEquipmentTech(-0.1)
        self.units["horse_transport"] = BridgingEquipmentTech(-0.1)
        self.units["camel_transport"] = BridgingEquipmentTech(-0.1)
        self.units["SOV_horse_transport"] = BridgingEquipmentTech(-0.1)
        self.units["engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["motorized_engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.3)
        self.units["ss_motorized_engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.3)
        self.units["armored_engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.4)
        self.units["ss_engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["ss_armored_engineer_brigade"] = BridgingEquipmentTech(riverAttack = 0.4)
        self.units["mixed_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["motorized_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["armored_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["ss_mixed_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["ss_motorized_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)
        self.units["ss_armored_support_brigade"] = BridgingEquipmentTech(riverAttack = 0.1)

class AssaultWeapons:
    def __init__(self, level):
        def AssaultWeaponsTech(softAttack=0, hardAttack=0, toughness=0, fortAttack=0, urbanAttack=0, jungleAttack=0, forestAttack=0, bocageAttack=0):
            return Technology("Assault Weapons", softAttack = softAttack, hardAttack = hardAttack, toughness = toughness, fortAttack = fortAttack, 
                urbanAttack = urbanAttack, jungleAttack = jungleAttack, forestAttack = forestAttack, bocageAttack = bocageAttack)

        self.units = {}
        self.level = level
        self.units["engineer_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.05)
        self.units["airborne_engineer_bat"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.05)
        self.units["airborne_combined_arms_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.05)
        self.units["motorized_engineer_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.1)
        self.units["ss_motorized_engineer_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.1)
        self.units["armored_engineers_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.15)
        self.units["commando_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.1, 0.1, 0.05)
        self.units["ss_engineer_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.05, 0.05, 0.05)
        self.units["ss_armored_engineers_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.15, 0.15, 0.05, 0.05, 0.15)
        self.units["ss_commando_brigade"] = AssaultWeaponsTech(1.5, 0.8, 1.8, 0.1, 0.1, 0.1, 0.1, 0.05)
        self.units["motorized_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.05)
        self.units["ss_motorized_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.05)
        self.units["armored_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.1)
        self.units["ss_armored_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.1)
        self.units["mixed_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.05)
        self.units["ss_mixed_support_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.05, 0.05, 0.05, 0.05, 0.05)
        self.units["combined_arms_brigade"] = AssaultWeaponsTech(1.1, 0.1, 0.8, 0.1, 0.05, 0.05, 0.05, 0.05)

class VehicleReliability:
    def __init__(self, level):
        def VehicleReliabilityTech(organization=0, softness=0, toughness=0, defensiveness=0):
            return Technology("Truck and Prime Mover Reliability", organization=organization, softness=softness, toughness=toughness, defensiveness=defensiveness)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = VehicleReliabilityTech(0.5)
        self.units["GER_hftrack_transport"] = VehicleReliabilityTech(0.5)
        self.units["FRA_hftrack_transport"] = VehicleReliabilityTech(0.5)
        self.units["truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["civilian_truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["ENG_truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["GER_truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["USA_truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["FRA_truck_transport"] = VehicleReliabilityTech(0.5)
        self.units["light_transport"] = VehicleReliabilityTech(0.5)
        self.units["USA_light_transport"] = VehicleReliabilityTech(0.5)
        self.units["ITA_light_transport"] = VehicleReliabilityTech(0.5)
        self.units["fascist_militia_brigade"] = VehicleReliabilityTech(softness=-0.01)
        self.units["ger_sa_militia_brigade"] = VehicleReliabilityTech(softness=-0.01)
        self.units["ger_sa_militia_detachment"] = VehicleReliabilityTech(softness=-0.01)
        self.units["elite_light_infantry_battalion"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["elite_light_infantry_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_infantry_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["semi_motorized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["motorized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_motorized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["guard_motorized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["motorized_infantry_bat"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_motorized_infantry_bat"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["mechanized_infantry_bat"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_mechanized_infantry_bat"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["mechanized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_mechanized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["guard_mechanized_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["combined_arms_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["armored_car_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_armored_car_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["medium_artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["heavy_artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_medium_artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_heavy_artillery_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["anti_air_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_anti_air_brigade"] = VehicleReliabilityTech(toughness=0.2, defensiveness=1.1)
        self.units["anti_tank_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_anti_tank_brigade"] = VehicleReliabilityTech(toughness=0.2, defensiveness=1.1)
        self.units["heavy_anti_air_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_heavy_anti_air_brigade"] = VehicleReliabilityTech(toughness=0.2, defensiveness=1.1)
        self.units["heavy_anti_tank_brigade"] = VehicleReliabilityTech(toughness=0.1, defensiveness=1.1)
        self.units["ss_heavy_anti_tank_brigade"] = VehicleReliabilityTech(toughness=0.2, defensiveness=1.1)
        self.units["motorized_support_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_motorized_support_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_totenkopf"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_lssah"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_wiking"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_dasreich"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_hitlerjugend"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_frundsberg"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["ss_hohenstaufen"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["grossdeutschland_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["lehr_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["afrika_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["goering_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)
        self.units["NKVD_brigade"] = VehicleReliabilityTech(toughness=0.3, defensiveness=1.1)

class BodyArmour:
    def __init__(self, level):
        def BodyArmourTech(defensiveness, toughness):
            return Technology("Body Armour", defensiveness = defensiveness, toughness = toughness)

        self.units = {}
        self.level = level
        self.units["garrison_brigade"] = BodyArmourTech(1.2, .05)
        self.units["tropical_island_garrison_brigade"] = BodyArmourTech(1.2, .05)
        self.units["garrison_detachment"] = BodyArmourTech(1.2, .05)
        self.units["colonial_garrison_brigade"] = BodyArmourTech(1.2, .05)
        self.units["luftwaffe_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_garrison_brigade"] = BodyArmourTech(1.2, .05)
        self.units["militia_brigade"] = BodyArmourTech(1.2, .05)
        self.units["colonial_militia_brigade"] = BodyArmourTech(1.2, .05)
        self.units["fascist_militia_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ger_sa_militia_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ger_sa_militia_detachment"] = BodyArmourTech(1.2, .05)
        self.units["Communist_militia_brigade"] = BodyArmourTech(1.2, .05)
        self.units["infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["colonial_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["ss_infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["anzac_brigade"] = BodyArmourTech(1.2, .05)
        self.units["light_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["colonial_light_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["elite_light_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["elite_light_infantry_battalion"] = BodyArmourTech(1.2, .05)
        self.units["ss_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["airlanding_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["air_cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["bergsjaeger_brigade"] = BodyArmourTech(1.2, .05)
        self.units["colonial_bergsjaeger_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_bergsjaeger_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ski_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_ski_brigade"] = BodyArmourTech(1.2, .05)
        self.units["Gurkha_brigade"] = BodyArmourTech(1.2, .05)
        self.units["naval_infantry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["marine_brigade"] = BodyArmourTech(1.2, .05)
        self.units["paratrooper_brigade"] = BodyArmourTech(1.2, .05)
        self.units["airborne_combined_arms_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_paratrooper_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_paratrooper_brigade"] = BodyArmourTech(1.2, .05)
        self.units["commando_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_commando_brigade"] = BodyArmourTech(1.2, .05)
        self.units["engineer_brigade"] = BodyArmourTech(1.2, .05)
        self.units["airborne_engineer_bat"] = BodyArmourTech(1.2, .05)
        self.units["motorized_engineer_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_motorized_engineer_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_engineer_brigade"] = BodyArmourTech(1.2, .05)
        self.units["cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["colonial_cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ger_sa_cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_cavalry_brigade"] = BodyArmourTech(1.2, .05)
        self.units["motorcycle_recon_brigade"] = BodyArmourTech(0.8, .05)
        self.units["ss_motorcycle_recon_brigade"] = BodyArmourTech(0.8, .05)
        self.units["semi_motorized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["motorized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_motorized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_motorized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["mechanized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_mechanized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_mechanized_brigade"] = BodyArmourTech(1.2, .05)
        self.units["Recon_cavalry_brigade"] = BodyArmourTech(0.8, .05)
        self.units["ss_Recon_cavalry_brigade"] = BodyArmourTech(0.8, .05)
        self.units["ger_sa_cavalry_datachment"] = BodyArmourTech(0.8, .05)
        self.units["combined_arms_brigade"] = BodyArmourTech(1.2, .05)
        self.units["motorized_infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["ss_motorized_infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["mechanized_infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["ss_mechanized_infantry_bat"] = BodyArmourTech(1.2, .05)
        self.units["police_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_police_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_polizei"] = BodyArmourTech(1.2, .05)
        self.units["NKVD_brigade"] = BodyArmourTech(1.2, .05)
        self.units["partisan_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_prinz_eugen"] = BodyArmourTech(1.2, .05)
        self.units["ss_totenkopf"] = BodyArmourTech(1.2, .05)
        self.units["ss_lssah"] = BodyArmourTech(1.2, .05)
        self.units["ss_wiking"] = BodyArmourTech(1.2, .05)
        self.units["ss_dasreich"] = BodyArmourTech(1.2, .05)
        self.units["ss_frundsberg"] = BodyArmourTech(1.2, .05)
        self.units["ss_hohenstaufen"] = BodyArmourTech(1.2, .05)
        self.units["ss_hitlerjugend"] = BodyArmourTech(1.2, .05)
        self.units["gossdeutschland_brigade"] = BodyArmourTech(1.2, .05)
        self.units["lehr_brigade"] = BodyArmourTech(1.2, .05)
        self.units["afrika_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_florian_geyer"] = BodyArmourTech(1.2, .05)
        self.units["goering_brigade"] = BodyArmourTech(1.2, .05)
        self.units["hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["mot_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["mech_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["mountain_infantry_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["marine_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["para_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ger_sa_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_mot_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["ss_mech_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_mot_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_mech_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["guard_para_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["shock_hq_brigade"] = BodyArmourTech(1.2, .05)
        self.units["HQDEF_brigade"] = BodyArmourTech(1.2, .05)

class DefenseDesigns:
    def __init__(self, level):
        def DefenseDesignsTech(plainsDefense=0, riverDefense=0, arcticDefense=0, desertDefense=0, woodsDefense=0, forestDefense=0, jungleDefense=0, 
            hillsDefense=0, mountainDefense=0, bocageDefense=0, urbanDefense=0, marshDefense=0, amphibiousDefense=0, fortDefense=0):
            return Technology("Defenseive Position Designs", plainsDefense=plainsDefense, riverDefense=riverDefense, arcticDefense=arcticDefense,
                desertDefense=desertDefense, woodsDefense=woodsDefense, forestDefense=forestDefense, jungleDefense=jungleDefense, hillsDefense=hillsDefense,
                mountainDefense=mountainDefense, bocageDefense=bocageDefense, urbanDefense=urbanDefense, marshDefense=marshDefense, amphibiousDefense=amphibiousDefense,
                fortDefense=fortDefense)

        self.units = {}
        self.level = level
        self.units["garrison_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["tropical_island_garrison_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["garrison_detachment"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["colonial_garrison_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["heavy_artillery_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ss_heavy_artillery_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["luftwaffe_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ss_garrison_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["infantry_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["colonial_infantry_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["infantry_bat"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ss_infantry_bat"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["anzac_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ss_infantry_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["guard_infantry_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["Communist_militia_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["militia_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["colonial_militia_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["fascist_militia_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ger_sa_militia_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["ger_sa_militia_detachment"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)
        self.units["HQDEF_brigade"] = DefenseDesignsTech(0.05, 0.075, 0.05, 0.05, 0.06, 0.075, 0.125, 0.075, 0.1, 0.1, 0.1, 0.125, 0.125, 0.15)

class MotorizedSupport:
    def __init__(self, level):
        def MotorizedSupportTech(organization=0, hardAttack=0, toughness=0, defensiveness=0):
            return Technology("Motorised Support Units", organization=organization, hardAttack=hardAttack, toughness=toughness, defensiveness=defensiveness)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = MotorizedSupportTech(0.1)
        self.units["GER_hftrack_transport"] = MotorizedSupportTech(0.1)
        self.units["FRA_hftrack_transport"] = MotorizedSupportTech(0.1)
        self.units["truck_transport"] = MotorizedSupportTech(0.1)
        self.units["civilian_truck_transport"] = MotorizedSupportTech(0.1)
        self.units["ENG_truck_transport"] = MotorizedSupportTech(0.1)
        self.units["GER_truck_transport"] = MotorizedSupportTech(0.1)
        self.units["USA_truck_transport"] = MotorizedSupportTech(0.1)
        self.units["FRA_truck_transport"] = MotorizedSupportTech(0.1)
        self.units["light_transport"] = MotorizedSupportTech(0.1)
        self.units["USA_light_transport"] = MotorizedSupportTech(0.1)
        self.units["ITA_light_transport"] = MotorizedSupportTech(0.1)
        self.units["semi_motorized_brigade"] = MotorizedSupportTech(hardAttack=0.1)
        self.units["motorized_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_motorized_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["motorized_infantry_bat"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["artillery_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_artillery_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["medium_artillery_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["heavy_artillery_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["heavy_anti_air_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["heavy_anti_tank_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["anti_air_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["anti_tank_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_anti_air_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_anti_tank_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_motorized_infantry_bat"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_medium_artillery_brigade"] = MotorizedSupportTech(hardAttack=0.3)
        self.units["ss_heavy_artillery_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_heavy_anti_air_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_heavy_anti_tank_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["motorized_support_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_motorized_support_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["mechanized_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["mechanized_infantry_bat"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_mechanized_infantry_bat"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["guard_mechanized_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_mechanized_brigade"] = MotorizedSupportTech(hardAttack=0.2)
        self.units["ss_totenkopf"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_lssah"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["grossdeutschland_brigade"] = MotorizedSupportTech(toughness=0.24, defensiveness=1.1)
        self.units["lehr_brigade"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["afrika_brigade"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["goering_brigade"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_wiking"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_dasreich"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_hitlerjugend"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_frundsberg"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)
        self.units["ss_hohenstaufen"] = MotorizedSupportTech(toughness=0.24, defensiveness=0.3)

class IntegratedAFVBat:
    def __init__(self, level):
        def IntegratedAFVBatTech(hardAttack=0, toughness=0, piercing=0, armor=0):
            return Technology("Integrated AFV Battalion", hardAttack=hardAttack, toughness=toughness, piercing=piercing, armor=armor)

        self.units = {}
        self.level = level
        self.units["motorized_brigade"] = IntegratedAFVBatTech(2, 2.4, 2, 5)
        self.units["mechanized_brigade"] = IntegratedAFVBatTech(2.3, 2.8, 3, 6)
        self.units["combined_arms_brigade"] = IntegratedAFVBatTech(2.3, 2.6, 2, 5)
        self.units["ss_mechanized_brigade"] = IntegratedAFVBatTech(2.4, 3, 3, 6)
        self.units["guard_mechanized_brigade"] = IntegratedAFVBatTech(2.5, 3, 3, 6)
        self.units["ss_motorized_brigade"] = IntegratedAFVBatTech(2.2, 2.6, 2, 5)
        self.units["ss_totenkopf"] = IntegratedAFVBatTech(2.4, 2.8, 3, 6)
        self.units["ss_lssah"] = IntegratedAFVBatTech(2.4, 2.8, 3, 6)
        self.units["ss_wiking"] = IntegratedAFVBatTech(2.2, 2.8, 2, 5)
        self.units["ss_dasreich"] = IntegratedAFVBatTech(2.5, 2.8, 3, 6)
        self.units["ss_frundsberg"] = IntegratedAFVBatTech(2.2, 0.8, 2, 5)
        self.units["ss_hohenstaufen"] = IntegratedAFVBatTech(2.2, 2.6, 2, 5)
        self.units["ss_hitlerjugend"] = IntegratedAFVBatTech(2.2, 2.8, 2, 5)
        self.units["guard_motorized_brigade"] = IntegratedAFVBatTech(2.3, 2.6, 2, 5)
        self.units["grossdeutschland_brigade"] = IntegratedAFVBatTech(2.4, 3, 3, 6)
        self.units["lehr_brigade"] = IntegratedAFVBatTech(2.3, 2.8, 2, 5)
        self.units["afrika_brigade"] = IntegratedAFVBatTech(2.3, 2.8, 2, 5)
        self.units["goering_brigade"] = IntegratedAFVBatTech(2.3, 2.6, 2, 5)

class CamouflageDesigns:
    def __init__(self, level):
        def CamouflageDesignsTech(defensiveness=0, toughness=0, airDefense=0):
            return Technology("Camouflage Designs", defensiveness=defensiveness, toughness=toughness, airDefense=airDefense)

        self.units = {}
        self.level = level
        self.units["garrison_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["tropical_island_garrison_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["garrison_detachment"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["colonial_garrison_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["luftwaffe_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["ss_garrison_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["militia_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["colonial_militia_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["fascist_militia_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["ger_sa_militia_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["ger_sa_militia_detachment"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["Communist_militia_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["infantry_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["colonial_infantry_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["infantry_bat"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["ss_infantry_bat"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["anzac_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["light_infantry_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["colonial_light_infantry_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["elite_light_infantry_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["elite_light_infantry_battalion"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_infantry_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["guard_infantry_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["airlanding_infantry_brigade"] = CamouflageDesignsTech(0.68, 0.2, 3)
        self.units["air_cavalry_brigade"] = CamouflageDesignsTech(1, 0.3)
        self.units["bergsjaeger_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["colonial_bergsjaeger_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["ss_bergsjaeger_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["ski_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_ski_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["Gurkha_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["naval_infantry_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["marine_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["paratrooper_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["airborne_combined_arms_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["ss_paratrooper_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["guard_paratrooper_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["commando_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_commando_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["engineer_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["airborne_engineer_bat"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["motorized_engineer_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["ss_motorized_engineer_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["ss_engineer_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["cavalry_brigade"] = CamouflageDesignsTech(0.4, 0.15, 3)
        self.units["colonial_cavalry_brigade"] = CamouflageDesignsTech(0.4, 0.15, 3)
        self.units["ss_cavalry_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["ger_sa_cavalry_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["guard_cavalry_brigade"] = CamouflageDesignsTech(0.6, 0.25, 3)
        self.units["motorcycle_recon_brigade"] = CamouflageDesignsTech(0.3, 0.2, 3)
        self.units["ss_motorcycle_recon_brigade"] = CamouflageDesignsTech(0.3, 0.2, 3)
        self.units["semi_motorized_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["motorized_brigade"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["ss_motorized_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["guard_motorized_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["mechanized_brigade"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["ss_mechanized_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["guard_mechanized_brigade"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["Recon_cavalry_brigade"] = CamouflageDesignsTech(0.3, 0.2, 3)
        self.units["ss_Recon_cavalry_brigade"] = CamouflageDesignsTech(0.3, 0.2, 3)
        self.units["ger_sa_cavalry_datachment"] = CamouflageDesignsTech(0.3, 0.2, 3)
        self.units["combined_arms_brigade"] = CamouflageDesignsTech(0.8, 0.2, 3)
        self.units["motorized_infantry_bat"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["ss_motorized_infantry_bat"] = CamouflageDesignsTech(1.1, 0.15, 3)
        self.units["mechanized_infantry_bat"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["ss_mechanized_infantry_bat"] = CamouflageDesignsTech(0.8, 0.15, 3)
        self.units["police_brigade"] = CamouflageDesignsTech(0.4, 0.15, 3)
        self.units["ss_police_brigade"] = CamouflageDesignsTech(0.4, 0.15, 3)
        self.units["ss_polizei"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["NKVD_brigade"] = CamouflageDesignsTech(0.4, 0.25)
        self.units["partisan_brigade"] = CamouflageDesignsTech(0.4, 0.25, 3)
        self.units["ss_prinz_eugen"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_totenkopf"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_lssah"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_wiking"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_dasreich"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_frundsberg"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["ss_hohenstaufen"] = CamouflageDesignsTech(1, 0.25, 3)
        self.units["ss_hitlerjugend"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["gossdeutschland_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["lehr_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["afrika_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["ss_florian_geyer"] = CamouflageDesignsTech(0.675, 0.3, 3)
        self.units["goering_brigade"] = CamouflageDesignsTech(1, 0.3, 3)
        self.units["hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["mot_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["mech_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["armor_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["mountain_infantry_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["marine_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["para_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["ss_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["ger_sa_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["ss_mot_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["ss_mech_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["ss_pz_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["guard_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["guard_mot_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["guard_mech_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["guard_armor_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["guard_para_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["shock_hq_brigade"] = CamouflageDesignsTech(0.2, 0.075, 3)
        self.units["HQDEF_brigade"] = CamouflageDesignsTech(0.4, 0.15, 3)

class ImprovedSecUnits:
    def __init__(self, level):
        def ImprovedSecUnitsTech(softAttack=0, hardAttack=0, toughness=0):
            return Technology("Improved Security Units", softAttack=softAttack, hardAttack=hardAttack, toughness=toughness)

        self.units = {}
        self.level = level
        self.units["police_brigade"] = ImprovedSecUnitsTech(0.8, 0.8, 0.5)
        self.units["ss_police_brigade"] = ImprovedSecUnitsTech(0.8, 0.8, 0.5)
        self.units["NKVD_brigade"] = ImprovedSecUnitsTech(0.8, 0.8, 0.5)
        self.units["Communist_militia_brigade"] = ImprovedSecUnitsTech(0.6, 0.6, 0.5)
        self.units["militia_brigade"] = ImprovedSecUnitsTech(0.6, 0.6, 0.5)
        self.units["colonial_militia_brigade"] = ImprovedSecUnitsTech(0.6, 0.6, 0.5)
        self.units["fascist_milita_brigade"] = ImprovedSecUnitsTech(0.6, 0.6, 0.5)
        self.units["ger_sa_militia_brigade"] = ImprovedSecUnitsTech(0.6, 0.6, 0.5)
        self.units["ger_sa_militia_detachment"] = ImprovedSecUnitsTech(0.3, 0.3, 0.5)

# Artillery Techs that affect combat stats

class RangeFindingEquipment:
    def __init__(self, level):
        def RangeFindingEquipmentTech(hardAttack=0, defensiveness=0, toughness=0, piercing=0):
            return Technology("Range Finding Equipment", hardAttack=hardAttack, defensiveness=defensiveness, toughness=toughness, piercing=piercing)

        self.units = {}
        self.level = level
        self.units["armored_support_brigade"] = RangeFindingEquipmentTech(0.15, 0.3, 0.25)
        self.units["motorized_support_brigade"] = RangeFindingEquipmentTech(0.15, 0.3, 0.25)
        self.units["heavy_anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["engineer_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["motorized_engineer_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["sp_anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["armored_engineers_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["anti_tank_brigade"] = RangeFindingEquipmentTech(1, 0.2, 0.1, 1)
        self.units["heavy_anti_tank_brigade"] = RangeFindingEquipmentTech(1, 0.2, 0.1, 1)
        self.units["rocket_artillery_brigade"] = RangeFindingEquipmentTech(0.1, 0.3, 0.1)
        self.units["ss_motorized_support_brigade"] = RangeFindingEquipmentTech(0.15, 0.3, 0.25)
        self.units["ss_armored_support_brigade"] = RangeFindingEquipmentTech(0.15, 0.3, 0.25)
        self.units["ss_heavy_anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["ss_anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["ss_engineer_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["ss_motorized_engineer_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["ss_sp_anti_air_brigade"] = RangeFindingEquipmentTech(0.1, 0.2, 0.1)
        self.units["ss_armored_engineers_brigade"] = RangeFindingEquipmentTech(0.1, 0.8, 0.2)
        self.units["ss_anti_tank_brigade"] = RangeFindingEquipmentTech(1, 0.2, 0.1, 1)
        self.units["ss_heavy_anti_tank_brigade"] = RangeFindingEquipmentTech(1, 0.2, 0.1, 1)
        self.units["ss_rocket_artillery_brigade"] = RangeFindingEquipmentTech(0.1, 0.3, 0.1)

class ArtilleryBarrellAmmo:
    def __init__(self, level):
        def ArtilleryBarrellAmmoTech(organization=0, softAttack=0):
            return Technology("Artillery Barrell and Ammunition", organization = organization, softAttack = softAttack)

        self.units = {}
        self.level = level
        self.units["hftrack_transport"] = ArtilleryBarrellAmmoTech(-.4)
        self.units["GER_hftrack_transport"] = ArtilleryBarrellAmmoTech(-.4)
        self.units["FRA_hftrack_transport"] = ArtilleryBarrellAmmoTech(-.4)
        self.units["truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["civilian_truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["ENG_truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["GER_truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["USA_truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["FRA_truck_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["light_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["GER_light_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["USA_light_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["ITA_light_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["horse_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["camel_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["SOV_horse_transport"] = ArtilleryBarrellAmmoTech(-.2)
        self.units["anti_air_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["heavy_anti_air_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["sp_anti_air_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["motorized_support_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.8)
        self.units["armored_support_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.8)
        self.units["engineer_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["airborne_engineer_bat"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["motorized_engineer_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["armored_engineers_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["anti_tank_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_anti_air_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_heavy_anti_air_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_motorized_support_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.8)
        self.units["ss_armored_support_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.8)
        self.units["ss_engineer_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_motorized_engineer_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_armored_engineers_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)
        self.units["ss_anti_tank_brigade"] = ArtilleryBarrellAmmoTech(softAttack=0.2)

class ArtilleryCarriageDesigns:
    def __init__(self, level):
        def ArtilleryCarriageDesignsTech(organization=0, hardAttack=0, defensiveness=0, toughness=0):
            return Technology(name="Artillery Carriage Designs", organization=organization, hardAttack=hardAttack, defensiveness=defensiveness, toughness=toughness)

        self.units["hftrack_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["GER_hftrack_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["FRA_hftrack_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["civilian_truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["ENG_truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["GER_truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["USA_truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["FRA_truck_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["light_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["GER_light_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["USA_light_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["ITA_light_transport"] = ArtilleryCarriageDesignsTech(0.5)
        self.units["horse_transport"] = ArtilleryCarriageDesignsTech(1)
        self.units["camel_transport"] = ArtilleryCarriageDesignsTech(1)
        self.units["SOV_horse_transport"] = ArtilleryCarriageDesignsTech(1)
        self.units["motorized_support_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.15, defensiveness=0.7, toughness=0.15)
        self.units["armored_support_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.15, defensiveness=0.7, toughness=0.15)
        self.units["ss_armored_support_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.15, defensiveness=0.7, toughness=0.15)
        self.units["ss_motorized_support_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.15, defensiveness=0.7, toughness=0.15)
        self.units["heavy_anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["sp_anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["engineer_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.2)
        self.units["motorized_engineer_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.2)
        self.units["armored_engineers_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.3)
        self.units["anti_tank_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.5, defensiveness=0.6, toughness=0.1)
        self.units["heavy_anti_tank_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.5, defensiveness=0.6, toughness=0.1)
        self.units["rocket_artillery_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.7, toughness=0.1)
        self.units["ss_heavy_anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["ss_anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["ss_sp_anti_air_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.5, toughness=0.1)
        self.units["ss_engineer_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.2)
        self.units["ss_motorized_engineer_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.2)
        self.units["ss_armored_engineers_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.8, toughness=0.4)
        self.units["ss_anti_tank_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.5, defensiveness=0.6, toughness=0.1)
        self.units["ss_heavy_anti_tank_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.5, defensiveness=0.6, toughness=0.1)
        self.units["ss_rocket_artillery_brigade"] = ArtilleryCarriageDesignsTech(hardAttack=0.1, defensiveness=0.7, toughness=0.1)

class HeavyArtilleryEmplacements:
    def __init__(self, level):
        def HeavyArtilleryEmplacementsTech(defensiveness=0, plainsDefense=0, riverDefense=0, urbanDefense=0, arcticDefense=0, desertDefense=0, woodsDefense=0,
            forestDefense=0, jungleDefense=0, hillsDefense=0, mountainDefense=0, marshDefense=0, fortDefense=0):
            return Technology("Heavy Artillery Emplacements", defensiveness=defensiveness, plainsDefense=plainsDefense, riverDefense=riverDefense, urbanDefense=urbanDefense,
                arcticDefense=arcticDefense, desertDefense=desertDefense, woodsDefense=woodsDefense, forestDefense=forestDefense, jungleDefense=jungleDefense,
                hillsDefense=hillsDefense, mountainDefense=mountainDefense, marshDefense=marshDefense, fortDefense=fortDefense)

        self.units = {}
        self.level = level
        self.units["artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=3, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)
        self.units["medium_artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=4.5, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)
        self.units["ss_medium_artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=4.5, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)
        self.units["heavy_artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=6, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)
        self.units["ss_artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=3, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)
        self.units["ss_heavy_artillery_brigade"] = HeavyArtilleryEmplacementsTech(defensiveness=6, plainsDefense=0.15, riverDefense=0.15, urbanDefense=0.05, arcticDefense=0.15,
            desertDefense=0.15, woodsDefense=0.15, forestDefense=0.15, jungleDefense=0.15, hillsDefense=0.15, mountainDefense=0.15, marshDefense=0.15, fortDefense=0.15)

class ArtilleryFireControl:
    def __init__(self, level):
        def ArtilleryFireControlTech(softAttack=0, defensiveness=0, width=0, plainsAttack=0, plainsDefense=0, riverAttack=0, riverDefense=0, urbanAttack=0, urbanDefense=0,
            arcticAttack=0, arcticDefense=0, desertAttack=0, desertDefense=0, woodsAttack=0, woodsDefense=0, forestAttack=0, forestDefense=0, jungleAttack=0, jungleDefense=0,
            hillsAttack=0, hillsDefense=0, mountainAttack=0, mountainDefense=0, marshAttack=0, marshDefense=0, fortAttack=0, fortDefense=0):
            return Technology("Artillery Fire Control Techniques", softAttack=softAttack, defensiveness=defensiveness, width=width, plainsAttack=plainsAttack, 
                plainsDefense=plainsDefense, riverAttack=riverAttack, riverDefense=riverDefense, urbanAttack=urbanAttack, urbanDefense=urbanDefense, arcticAttack=arcticAttack,
                arcticDefense=arcticDefense, desertAttack=desertAttack, desertDefense=desertDefense, woodsAttack=woodsAttack, woodsDefense=woodsDefense, forestAttack=forestAttack,
                forestDefense=forestDefense, jungleAttack=jungleAttack, jungleDefense=jungleDefense, hillsAttack=hillsAttack, hillsDefense=hillsDefense, mountainAttack=mountainAttack,
                mountainDefense=mountainDefense, marshAttack=marshAttack, marshDefense=marshDefense, fortAttack=fortAttack, fortDefense=fortDefense)

        self.units = {}
        self.level = level
        self.units["artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["pack_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.4, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["medium_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["ss_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["ss_pack_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.4, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["ss_medium_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["armored_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["motorized_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["mixed_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["airborne_artillery_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["ss_mixed_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["ss_motorized_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["ss_armored_support_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.8)
        self.units["rocket_artillery_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.4)
        self.units["sp_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["sp_rct_artillery_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.4)
        self.units["guard_sp_rct_artillery_brigade"] = ArtilleryFireControlTech(softAttack=3.00, defensiveness=1.6)
        self.units["ss_rocket_artillery_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.4)
        self.units["ss_sp_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=1.8, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["ss_sp_rct_artillery_brigade"] = ArtilleryFireControlTech(softAttack=2.00, defensiveness=1.5)
        self.units["heavy_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=3.6, width=-0.5, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)
        self.units["ss_heavy_artillery_brigade"] = ArtilleryFireControlTech(defensiveness=3.6, width=-0.5, plainsAttack=0.1, plainsDefense=0.1, riverAttack=0.1, riverDefense=0.1, urbanAttack=0.1,
            arcticAttack=0.1, arcticDefense=0.1, desertAttack=0.1, desertDefense=0.1, woodsAttack=0.1, woodsDefense=0.1, forestAttack=0.1, forestDefense=0.1, jungleAttack=0.1,
            jungleDefense=0.1, hillsAttack=0.1, hillsDefense=0.1, mountainAttack=0.1, mountainDefense=0.1, marshAttack=0.1, marshDefense=0.1, fortAttack=0.1, fortDefense=0.1)